/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/Base/AppFooter.vue')['default']
    DefaultHeader: typeof import('./components/Base/DefaultHeader.vue')['default']
    EquipmentsList: typeof import('./components/Equipments/EquipmentsList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MenuSideBar: typeof import('./components/Base/MenuSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WellcomeAiko: typeof import('./components/WellcomeAiko.vue')['default']
  }
}
