/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/Base/AppFooter.vue')['default']
    BaseCardTitle: typeof import('./components/Base/BaseCardTitle.vue')['default']
    BaseEquipmentStatus: typeof import('./components/Base/BaseEquipmentStatus.vue')['default']
    BaseLoadingSpinner: typeof import('./components/Base/BaseLoadingSpinner.vue')['default']
    DefaultHeader: typeof import('./components/Base/DefaultHeader.vue')['default']
    EquipmentCard: typeof import('./components/Equipments/EquipmentCard.vue')['default']
    EquipmentModal: typeof import('./components/Equipments/EquipmentModal.vue')['default']
    EquipmentsList: typeof import('./components/Equipments/EquipmentsList.vue')['default']
    EquipmentStateTable: typeof import('./components/Equipments/EquipmentStateTable.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LeafletMap: typeof import('./components/Map/LeafletMap.vue')['default']
    MenuSideBar: typeof import('./components/Base/MenuSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WellcomeAiko: typeof import('./components/WellcomeAiko.vue')['default']
  }
}
